GoogleCloudPlatform/native-image-support-java

google-cloud-graalvm-samples/google-cloud-graalvm-pubsub-sample/pom.xml, google-cloud-graalvm-samples/google-cloud-graalvm-pubsub-sample/src/main/java/com/example/Driver.java, google-cloud-graalvm-samples/google-cloud-graalvm-pubsub-sample/src/main/java/com/example/PubSubSampleApplication.java, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-support/pom.xml, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/jni-config.json, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/reflect-config.json, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/resource-config.json, pom.xml
The initial commit of GraalVM configurations, a sample, and project structure.
=> Initial commit of GraalVM configuration

google-cloud-graalvm-samples/google-cloud-graalvm-pubsub-sample/pom.xml, google-cloud-graalvm-samples/google-cloud-graalvm-pubsub-sample/src/main/java/com/example/PubSubSampleApplication.java
Expands the covered code paths in the Pub/Sub sample.
=> Expand the covered codepaths in the Pub/Sub Sample

.github/workflows/maven.yml
Creates the Github Actions CI to compile and run the sample apps.
=> Create Github Actions CI

google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/jni-config.json, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/reflect-config.json
Doing a first pass, trying to cut down some unnecessary GraalVM configuration.
=> Delete extra Graal configurations

google-cloud-graalvm-samples/storage-sample/src/main/java/com/example/StorageSampleApplication.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/GoogleJsonClientFeature.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/StorageFeature.java
Add more codepaths in the Storage sample and enhance Storage reflection configs.
=> Improve Storage Support

google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml
Fixes some errors in the pom.xml of the samples from when the refactoring was done earlier.
=> Fix the samples parents module structure

.kokoro/stage.sh
Removes an unused profile in the `staging.sh` script.
=> Remove unused profile in staging script

pom.xml
Add missing information in the parent pom needed for release.
I.e. name/description, scm fields, license, etc.
=> Add missing information in parent pom for release

.kokoro/promote.cfg, .kokoro/promote.sh
Fixes the promote and drop actions for the repo.
* Adds the missing promote scripts.
* Add `-P release` profile to drop.sh
=> Fix artifact promote and drop actions

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-support/pom.xml, pom.xml
Updates the versions and docs for the 0.1.0 release.
=> Upgrade versions for 0.1.0 release

google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/README.md
Fixes broken links in the samples docs.
=> Fix broken sample links

.cloudbuild/graal-build.yaml, .cloudbuild/std-build.yaml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/src/main/java/com/example/SecretManagerSampleApplication.java
Add a sample demonstrating Secret Manager usage.
Secret Manager is a gax/gapic-level library.
=> Add sample demonstrating secret manager usage

google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/src/main/java/com/example/StorageSampleApplication.java
Fix the cleanup step in the storage sample - the bucket needs to be deleted at the end, not the file.
=> Fix cleanup step in storage sample

.cloudbuild/graal-build.yaml, .cloudbuild/std-build.yaml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/src/main/java/com/example/FirestoreSampleApplication.java, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml
Add working GraalVM sample using the Firestore Client Libraries.
=> Add firestore sample

.cloudbuild/graal-build.yaml, .cloudbuild/std-build.yaml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/src/main/java/com/example/BigQuerySampleApplication.java, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/BigQueryFeature.java
Add GraalVM-compatible sample using BigQuery.
=> Add a working BigQuery sample

README.md
Update the README for version `0.2.0`.
=> Update README for 0.2.0

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-support/pom.xml, pom.xml
Bump the snapshot version from `0.2.0-SNAPSHOT` to `0.3.0-SNAPSHOT`.
=> Bump snapshot versions

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-integration-test/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-support/pom.xml, pom.xml
Increment the version number after release.
=> Increment versions after release.

RELEASING.md
This copies over the releasing guide from our repositories as reference.
=> Add releasing guide

README.md
Add another link to secret manager sample
=> Add link to Secret Manager sample

.cloudbuild/graal-build.yaml, .github/workflows/maven.yml, google-cloud-graalvm-samples/pom.xml, pom.xml
Upgrade project dependency versions to latest -- GraalVM compiler version and `libraries-bom` version.
=> Upgrade project dependency versions

google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/core/ProtobufMessageFeature.java
Fixes a bug where we were null-checking the wrong variable.
=> Fix null check in ProtobufMessageFeature

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-functions-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-integration-test/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-support/pom.xml, pom.xml
=> Upgrade version numbers after release

.cloudbuild/graal-build.yaml, .cloudbuild/std-build.yaml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-sql-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-sql-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-sql-sample/src/main/java/com/example/CloudSqlSampleApplication.java, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/NativeImageUtils.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/core/GoogleJsonClientFeature.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/gcp/CloudSqlFeature.java
Add initial support for the Cloud SQL connector libraries for MySQL.
=> Add support for Cloud SQL

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-functions-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-sql-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-integration-test/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-support/pom.xml, pom.xml
Increment version numbers to `0.6.0-SNAPSHOT` after release.
=> Increment version numbers after release

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-functions-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-sql-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-integration-test/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-support/pom.xml, pom.xml
Bumps version numbers after release.
=> Bump versions after release 0.6.0

pom.xml
This updates the sonatype endpoints which should fix our continuous build.
=> Update Sonatype Endpoints

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, native-image-samples/native-image-samples-client-library/bigquery-sample/pom.xml, native-image-samples/native-image-samples-client-library/bigtable-sample/pom.xml, native-image-samples/native-image-samples-client-library/cloud-functions-sample/pom.xml, native-image-samples/native-image-samples-client-library/cloud-sql-sample/pom.xml, native-image-samples/native-image-samples-client-library/datastore-sample/pom.xml, native-image-samples/native-image-samples-client-library/firestore-sample/pom.xml, native-image-samples/native-image-samples-client-library/logging-sample/pom.xml, native-image-samples/native-image-samples-client-library/pom.xml, native-image-samples/native-image-samples-client-library/pubsub-sample/pom.xml, native-image-samples/native-image-samples-client-library/secretmanager-sample/pom.xml, native-image-samples/native-image-samples-client-library/spanner-sample/pom.xml, native-image-samples/native-image-samples-client-library/storage-sample/pom.xml, native-image-samples/native-image-samples-client-library/tasks-sample/pom.xml, native-image-samples/native-image-samples-client-library/trace-sample/pom.xml, native-image-samples/native-image-samples-quarkus/pom.xml, native-image-samples/native-image-samples-quarkus/quarkus-integration-test/pom.xml, native-image-samples/native-image-samples-quarkus/quarkus-pubsub-sample/README.md, native-image-samples/native-image-samples-quarkus/quarkus-pubsub-sample/pom.xml, native-image-samples/native-image-samples-spring/pom.xml, native-image-samples/native-image-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, native-image-samples/pom.xml, native-image-support/pom.xml, pom.xml
This bumps the snapshot versions to 0.9.0 after release.
=> Bump snapshot version to 0.9.0

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, native-image-samples/native-image-samples-client-library/bigquery-sample/pom.xml, native-image-samples/native-image-samples-client-library/bigtable-sample/pom.xml, native-image-samples/native-image-samples-client-library/cloud-functions-sample/pom.xml, native-image-samples/native-image-samples-client-library/cloud-sql-postgres-sample/pom.xml, native-image-samples/native-image-samples-client-library/cloud-sql-sample/pom.xml, native-image-samples/native-image-samples-client-library/datastore-sample/pom.xml, native-image-samples/native-image-samples-client-library/firestore-sample/pom.xml, native-image-samples/native-image-samples-client-library/logging-sample/pom.xml, native-image-samples/native-image-samples-client-library/pom.xml, native-image-samples/native-image-samples-client-library/pubsub-sample/pom.xml, native-image-samples/native-image-samples-client-library/secretmanager-sample/pom.xml, native-image-samples/native-image-samples-client-library/spanner-sample/pom.xml, native-image-samples/native-image-samples-client-library/storage-sample/pom.xml, native-image-samples/native-image-samples-client-library/tasks-sample/pom.xml, native-image-samples/native-image-samples-client-library/trace-sample/pom.xml, native-image-samples/native-image-samples-quarkus/pom.xml, native-image-samples/native-image-samples-quarkus/quarkus-integration-test/pom.xml, native-image-samples/native-image-samples-quarkus/quarkus-pubsub-sample/README.md, native-image-samples/native-image-samples-quarkus/quarkus-pubsub-sample/pom.xml, native-image-samples/native-image-samples-spring/pom.xml, native-image-samples/native-image-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, native-image-samples/pom.xml, native-image-support/pom.xml, pom.xml
This increments the project version to `0.10.0` after release.
=> Increment project version to 0.10.0

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, native-image-samples/native-image-samples-client-library/bigquery-sample/pom.xml, native-image-samples/native-image-samples-client-library/bigtable-sample/pom.xml, native-image-samples/native-image-samples-client-library/cloud-functions-sample/pom.xml, native-image-samples/native-image-samples-client-library/cloud-sql-postgres-sample/pom.xml, native-image-samples/native-image-samples-client-library/cloud-sql-sample/pom.xml, native-image-samples/native-image-samples-client-library/datastore-sample/pom.xml, native-image-samples/native-image-samples-client-library/firestore-sample/pom.xml, native-image-samples/native-image-samples-client-library/logging-sample/pom.xml, native-image-samples/native-image-samples-client-library/pom.xml, native-image-samples/native-image-samples-client-library/pubsub-sample/pom.xml, native-image-samples/native-image-samples-client-library/secretmanager-sample/pom.xml, native-image-samples/native-image-samples-client-library/spanner-sample/pom.xml, native-image-samples/native-image-samples-client-library/storage-sample/pom.xml, native-image-samples/native-image-samples-client-library/tasks-sample/pom.xml, native-image-samples/native-image-samples-client-library/trace-sample/pom.xml, native-image-samples/native-image-samples-quarkus/pom.xml, native-image-samples/native-image-samples-quarkus/quarkus-integration-test/pom.xml, native-image-samples/native-image-samples-quarkus/quarkus-pubsub-sample/README.md, native-image-samples/native-image-samples-quarkus/quarkus-pubsub-sample/pom.xml, native-image-samples/native-image-samples-spring/pom.xml, native-image-samples/native-image-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, native-image-samples/pom.xml, native-image-support/pom.xml, pom.xml
Bumps project to version `0.11.0-SNAPSHOT`.
=> Bump versions after release

.cloudbuild/graal-build.yaml, pom.xml
CVE: https://security.snyk.io/vuln/SNYK-JAVA-ORGGRAALVMSDK-2769618
=> Use graal-sdk 21.3.2 to address CVE
