google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/reflect-config.json
Adds the JSON token classes to reflection config to enable correct creation of authentication tokens when using service account authentication.
This change will be verified once I merge in and then #6 will start working.
=> Add reflection config for JSON token classes

google-cloud-graalvm-samples/google-cloud-graalvm-pubsub-sample/pom.xml, google-cloud-graalvm-support/pom.xml, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/jni-config.json, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/reflect-config.json, pom.xml
Modify configurations to support `grpc-netty-shaded`.
The pom file for the sample is now a lot more simplified: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/compare/use-netty-shaded?expand=1#diff-bd6c1dc3b6eccc9a9c14673eee04261e
I tried to support both non-shaded and shaded versions of `grpc-netty` but it was a bit too complicated for now. I think the first iteration of the project should just support `grpc-netty-shaded` which is what is inherited by the client libraries.
=> Modify configs to support grpc-netty-shaded

README.md, google-cloud-graalvm-samples/google-cloud-graalvm-pubsub-sample/pom.xml
Upgrade the `libraries-bom` version to `11.0.0` so users don't need to override grpc-netty-shaded version.
=> Upgrade libraries bom version

.github/workflows/maven.yml, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-samples/trace-sample/pom.xml, google-cloud-graalvm-samples/trace-sample/src/main/java/com/example/TraceSampleApplication.java
Add another sample using the Trace Client libraries.
Note that this worked out of the box without any config modifications, but this by itself is not too useful it seems; this trace library is a bit low-level and people would likely use it through opencensus or our spring-cloud-gcp-starter-trace.
=> Add sample using the Trace Client Libraries

google-cloud-graalvm-samples/README.md, google-cloud-graalvm-samples/pubsub-sample/README.md, google-cloud-graalvm-samples/trace-sample/README.md
This moves the setup instructions (shared across samples) to the samples-parent README.
=> Move setup instructions docs to samples-parent directory

.github/workflows/maven.yml
This should resolve some timeout errors that have occurred: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/runs/1216958300
=> Increase timeout for graal build

src/checkstyle/custom-checks.xml
Add the new line to EOF check to our checkstyle.
It seems like the check only gets to applied to Java source files but not onto `pom.xml` files based on our past research here:
https://github.com/spring-cloud/spring-cloud-gcp/issues/338
But at least now our source files will get checked.
=> Add NewLineAtEndOfFile to Checkstyle

.cloudbuild/graal-build.yaml, .github/workflows/maven.yml, pom.xml
Upgrades the graalvm compiler version to `20.2.0` for the CI and add missing samples to CI.
=> Upgrade GraalVM version and add samples to CI

google-cloud-graalvm-samples/logging-sample/pom.xml, google-cloud-graalvm-samples/pubsub-sample/pom.xml, google-cloud-graalvm-samples/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/storage-sample/pom.xml, google-cloud-graalvm-samples/trace-sample/pom.xml, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/native-image.properties
Moves `-H:+AllowIncompleteClasspath` and `--report-unsupported-elements-at-runtime` to be shared as these settings are necessary to get compilation working.
=> Make certain native image args shared

google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/src/main/java/com/example/PubSubSampleApplication.java, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/src/main/java/com/example/PublishOperations.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/PubSubFeature.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/core/GoogleJsonClientFeature.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/core/GrpcNettyFeature.java
Adds more code paths exercised by the Pub/Sub client libraries.
I added all of the snippets found here: https://github.com/googleapis/java-pubsub/tree/master/samples/snippets/src/main/java/pubsub
The code coverage should be much better at this point.
=> Add more coverage for Pub/Sub library calls

README.md, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/NativeImageUtils.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/StorageFeature.java
This introduces a utility for scanning classes under a package and registering them for reflection.
All classes under `com.google.api.services.storage.model` need to be registered.
```
registerPackageForReflection(
access, "com.google.api.services.storage.model");
```
Achieves parity with [storage configs of quarkus extension](https://github.com/quarkiverse/quarkiverse-google-cloud-services/blob/master/storage/deployment/src/main/java/io/quarkiverse/googlecloudservices/storage/deployment/StorageBuildSteps.java).
=> Add method for registering classes under package for reflection

.cloudbuild/std-build.yaml, .github/workflows/maven.yml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-samples/pom.xml, google-cloud-graalvm-support/pom.xml, pom.xml
Downgrade version to `0.1.0-SNAPSHOT`.
I'm interested in doing this so I can release an (early-access) version `0.1.0` that can be used by the quarkiverse extension. So users do not have to rely on sonatype snapshots repo.
=> Downgrade version to 0.1.0-SNAPSHOT

google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/pom.xml
I realized that the libraries-bom was already managed in the samples parent, no need to duplicate it in the client-library samples.
=> Remove libraries-bom management from the samples

google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/src/main/java/com/example/TraceSampleApplication.java
Remove unnecessary sample application arguments. Also add `--initialize-at-build-time` which is a stricter level of compilation in GraalVM. Quarkus uses `--initialize-at-build-time` by default.
=> Simplify sample application arguments

google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml
Moves the Java packaging plugins to the shared samples parent to reduce redundancy.
=> Move Java packaging plugins to shared parent pom for samples

.cloudbuild/graal-build.yaml, .github/workflows/maven.yml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/pom.xml, google-cloud-graalvm-samples/graalvm-samples-quarkus/quarkus-pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-support/pom.xml, pom.xml
This upgrades the project to using GraalVM 20.3.0.
Also marks the GraalVM SDK dependency as `provided`.
The `provided` correctly excludes the dependency from the compiled sources (so no need for those exclusions anymore) and also fixes the issue with Quarkus mentioned in https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/issues/59.
Fixes https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/issues/59.
=> Upgrade to GraalVM 20.3.0 and fix GraalVM SDK scope

.github/workflows/maven.yml, google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample/src/main/java/com/example/DatastoreSampleApplication.java
Fix the Github actions build.
The previous gcloud github action appears to be deprecated, so switching to the new one. Also modify the datastore sample to avoid it flaking when run in the CI.
=> Fix Github Actions build

.cloudbuild/std-build.yaml
See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html - `package` is already done in order to satisfy `install`
=> Remove 'package' maven step because it's already done in 'install' phase

.cloudbuild/graal-build.yaml, .cloudbuild/std-build.yaml, README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/src/main/java/com/example/TasksSampleApplication.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/CloudTasksFeature.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/core/GrpcNettyFeature.java
Opening this early to get some feedback. The queue and task creation works flawlessly, but I ran into issues when attempting to convert `Queue` and `Task` classes into strings. 
At runtime, the natively built image would fail complaining about getters not being found, both within the class in question and the builder, for example `Queue$Builder`.  This is, presumably, because the way gRPC classes are converted to strings requires reflective access. For example, the Task object is printed like this:
```
name: "projects/xxxxxxxx/locations/us-central1/queues/graal-test-queue-6685/tasks/56217623861818533241"
http_request {
url: "https://google.com/"
http_method: GET
headers {
key: "User-Agent"
value: "Google-Cloud-Tasks"
}
}
schedule_time {
seconds: 1613187863
nanos: 685055000
}
create_time { …
```
=> Cloud Tasks sample

google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/substitutions/ApiClientVersionSubstitutions.java, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/native-image.properties
Use an alternate approach for setting the JSON client language headers.
The previous method references classes from `jdk.vm.ci.meta` but this seems to break the Kokoro build. Standard JDK 8 does not seem to have access to classes in this package.
=> Fix JSON language header override method (take 2)

README.md, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/pom.xml, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/ProtobufMessageFeature.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/SpannerFeature.java, google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/core/GrpcNettyFeature.java
This makes the `ProtobufMessageFeature` opt-in.
It is a good practice to minimize the amount of reflection you register; In the vast majority of cases, you only need to register proto objects for reflection if you want to print/log them.
This has a big impact on the resulting image size; reduces the image size of the [Quarkus sample](https://github.com/quarkiverse/quarkus-google-cloud-services/tree/master/integration-tests) from 150mb to 95mb. Also it reduces the compilation time from ~5 minutes to around 3-4 mins.
=> Makes the ProtobufMessageFeature optional

.kokoro/stage.sh
This adds the `release` profile to the Kokoro staging step.
Adding the profile will exclude the samples from being installed since they are not needed for staging.
=> Exclude installing samples from Kokoro staging step

.kokoro/stage.sh
Removes the install step in the Kokoro staging job.
The `install` is not necessary because `mvn deploy` [includes all of the maven lifecycle phases including install](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#a-build-lifecycle-is-made-up-of-phases).
=> Remove install step in Kokoro staging job

.cloudbuild/graal-build.yaml, .cloudbuild/std-build.yaml
Improves the Cloud Build maven caching.
This proposed method uploads/downloads a cached tar file containing the cache which is much faster than `gsutil` with `rsync`.
Fixes #111.
=> Improve Cloud Build Maven Caching

google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/core/OpenCensusFeature.java, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/resource-config.json
Certain client libraries invoke OpenCensus such as Pub/Sub: https://github.com/googleapis/java-pubsub/blob/134273dc751e3bfb23c77384c8173c7b693a9757/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/OpenCensusUtil.java
Need some reflection configs to handle these cases.
=> Fix OpenCensus Support

google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/core/OpenCensusFeature.java
Fix the class to check for on the classpath to determine if opencensus is used. Changing it to the concrete implementation class instead of the `Tag` interface since they live in separate libraries.
=> Fix indicator class for opencensus feature

.kokoro/stage.sh
This adds the `-P release` profile to the `mvn version` command to avoid the samples from being processed by Maven unnecessarily.
=> Add release profile to staging script

google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-functions-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-sql-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml, google-cloud-graalvm-samples/graalvm-samples-spring/spring-cloud-gcp-trace-sample/pom.xml, google-cloud-graalvm-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/native-image.properties
This change enables HTTPS support by default (via `--enable-url-protocols=https,http`) since it is required for any application that requires network connectivity (such as connecting to GCP services).
This no longer needs to be set by the end user manually.
=> Enable http and https support by default

google-cloud-graalvm-support/src/main/java/com/google/cloud/graalvm/features/SpannerFeature.java
This changeset fixes and closes #205, which reports some missing resources for `SpannerFeature.java`.
Added resources:
=> Fix: Spanner Resources

.github/workflows/maven.yml
Use a different GHA step for GraalVM installation as the old one appears to have broken.
=> Use different GHA step for GraalVM installation

native-image-support/src/main/java/com/google/cloud/nativeimage/features/ProtobufMessageFeature.java, native-image-support/src/main/java/com/google/cloud/nativeimage/features/SpannerFeature.java, native-image-support/src/main/java/com/google/cloud/nativeimage/features/cloudfunctions/CloudFunctionsFeature.java, native-image-support/src/main/java/com/google/cloud/nativeimage/features/core/GoogleJsonClientFeature.java, native-image-support/src/main/java/com/google/cloud/nativeimage/features/core/GrpcNettyFeature.java, native-image-support/src/main/java/com/google/cloud/nativeimage/features/core/OpenCensusFeature.java, native-image-support/src/main/java/com/google/cloud/nativeimage/features/gcp/CloudSqlFeature.java
Make the GraalVM features have package-private visibility;. These classes are never meant to be used in code; avoid exposure on classpath and IDE autocomplete.
=> Reduce visibility of GraalVM features

native-image-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/native-image.properties
Marks Netty SSL-related classes to be initialized at runtime.
Resolves issue introduced in `grpc-netty-shaded` version 1.42.0. See example stacktrace: https://source.cloud.google.com/results/invocations/f4076bd5-de19-4a77-8569-a361fd92d3c4/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-accessapproval%2Fpresubmit%2Fgraalvm-native/log
=> Mark all Netty SSL-related classes as initialize-at-run-time

.github/workflows/maven.yml
`setup-gcloud` will be updating the branch name from master to main On 2022-04-05. This PR updates your GitHub Actions workflows to pin to v0 as recommended best practice [here](https://github.com/google-github-actions/setup-gcloud).
This change is already breaking our [CI runs](https://github.com/GoogleCloudPlatform/native-image-support-java/runs/5647662850).
=> Pin setup-gcloud to v0 instead of master

native-image-support/src/main/java/com/google/cloud/nativeimage/features/SpannerFeature.java, native-image-support/src/main/java/com/google/cloud/nativeimage/features/core/OpenCensusFeature.java, native-image-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/native-image.properties
The changes are derived from the following PR list in java-core: https://github.com/googleapis/java-core/pulls?q=is%3Apr+is%3Aclosed+author%3Ampeddada1+
=> Copy over configurations from java-core/native-image-support

pom.xml
Because this repo's minumum Java version is still 8.
=> Revert checkstyle to 9.3

native-image-support/src/main/java/com/google/cloud/nativeimage/features/core/GrpcNettyFeature.java
Fixes #393 
Reproducer of issue: https://github.com/suztomo/pubsub-sample-graal22.1-failure/pull/1.
The registration of `java.lang.management.ManagementFactory` was the root cause of the following problem in Pub/Sub and other libraries:
```
Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a PlatformManagedObject (a MXBean defined by the virtual machine) in the image heap. This bean is introspecting the VM that runs the image builder, i.e., a VM instance that is no longer available at image runtime. Class of disallowed object: com.sun.management.internal.HotSpotDiagnostic  To see how this object got instantiated use --trace-object-instantiation=com.sun.management.internal.HotSpotDiagnostic. The object was …
```
=> remove obsolete configurations to address GraalVM 22.1.0 breakage
